server:
  port : 9993

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5434/ticket
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

core:
  endpoint: "http://${CORE_HOST:localhost}:9992"

partners:
  best-tickets:
    endpoint: "http://${PARTNER_HOST:localhost}:9994"