server:
  port : 9991

core:
  endpoint: "http://${CORE_HOST:localhost}:9992"

ticket:
  endpoint: "http://${TICKET_HOST:localhost}:9993"

spring:
  cache:
    type: none

logging:
  level:
    com.zsoltbalvanyos: DEBUG